//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: test-expressions.proto

package testrunner.expressions;

@kotlin.jvm.JvmName("-initializearrayInstance")
public inline fun arrayInstance(block: testrunner.expressions.ArrayInstanceKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.ArrayInstance =
  testrunner.expressions.ArrayInstanceKt.Dsl._create(testrunner.expressions.TestExpressions.ArrayInstance.newBuilder()).apply { block() }._build()
public object ArrayInstanceKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: testrunner.expressions.TestExpressions.ArrayInstance.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: testrunner.expressions.TestExpressions.ArrayInstance.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): testrunner.expressions.TestExpressions.ArrayInstance = _builder.build()

    /**
     * <code>.TypeRepr elementTypeRepr = 1;</code>
     */
    public var elementTypeRepr: testrunner.expressions.TestExpressions.TypeRepr
      @JvmName("getElementTypeRepr")
      get() = _builder.getElementTypeRepr()
      @JvmName("setElementTypeRepr")
      set(value) {
        _builder.setElementTypeRepr(value)
      }
    /**
     * <code>.TypeRepr elementTypeRepr = 1;</code>
     */
    public fun clearElementTypeRepr() {
      _builder.clearElementTypeRepr()
    }
    /**
     * <code>.TypeRepr elementTypeRepr = 1;</code>
     * @return Whether the elementTypeRepr field is set.
     */
    public fun hasElementTypeRepr(): kotlin.Boolean {
      return _builder.hasElementTypeRepr()
    }

    /**
     * <code>int32 size = 2;</code>
     */
    public var size: kotlin.Int
      @JvmName("getSize")
      get() = _builder.getSize()
      @JvmName("setSize")
      set(value) {
        _builder.setSize(value)
      }
    /**
     * <code>int32 size = 2;</code>
     */
    public fun clearSize() {
      _builder.clearSize()
    }

    /**
     * <code>int32 address = 3;</code>
     */
    public var address: kotlin.Int
      @JvmName("getAddress")
      get() = _builder.getAddress()
      @JvmName("setAddress")
      set(value) {
        _builder.setAddress(value)
      }
    /**
     * <code>int32 address = 3;</code>
     */
    public fun clearAddress() {
      _builder.clearAddress()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun testrunner.expressions.TestExpressions.ArrayInstance.copy(block: testrunner.expressions.ArrayInstanceKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.ArrayInstance =
  testrunner.expressions.ArrayInstanceKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val testrunner.expressions.TestExpressions.ArrayInstanceOrBuilder.elementTypeReprOrNull: testrunner.expressions.TestExpressions.TypeRepr?
  get() = if (hasElementTypeRepr()) getElementTypeRepr() else null

