//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: test-expressions.proto

package testrunner.expressions;

@kotlin.jvm.JvmName("-initializeconstructorCall")
public inline fun constructorCall(block: testrunner.expressions.ConstructorCallKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.ConstructorCall =
  testrunner.expressions.ConstructorCallKt.Dsl._create(testrunner.expressions.TestExpressions.ConstructorCall.newBuilder()).apply { block() }._build()
public object ConstructorCallKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: testrunner.expressions.TestExpressions.ConstructorCall.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: testrunner.expressions.TestExpressions.ConstructorCall.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): testrunner.expressions.TestExpressions.ConstructorCall = _builder.build()

    /**
     * <code>.MethodRepr method = 1;</code>
     */
    public var method: testrunner.expressions.TestExpressions.MethodRepr
      @JvmName("getMethod")
      get() = _builder.getMethod()
      @JvmName("setMethod")
      set(value) {
        _builder.setMethod(value)
      }
    /**
     * <code>.MethodRepr method = 1;</code>
     */
    public fun clearMethod() {
      _builder.clearMethod()
    }
    /**
     * <code>.MethodRepr method = 1;</code>
     * @return Whether the method field is set.
     */
    public fun hasMethod(): kotlin.Boolean {
      return _builder.hasMethod()
    }

    /**
     * <code>.TypeRepr returnType = 2;</code>
     */
    public var returnType: testrunner.expressions.TestExpressions.TypeRepr
      @JvmName("getReturnType")
      get() = _builder.getReturnType()
      @JvmName("setReturnType")
      set(value) {
        _builder.setReturnType(value)
      }
    /**
     * <code>.TypeRepr returnType = 2;</code>
     */
    public fun clearReturnType() {
      _builder.clearReturnType()
    }
    /**
     * <code>.TypeRepr returnType = 2;</code>
     * @return Whether the returnType field is set.
     */
    public fun hasReturnType(): kotlin.Boolean {
      return _builder.hasReturnType()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ArgsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.Any args = 3;</code>
     */
     public val args: com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArgsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getArgsList()
      )
    /**
     * <code>repeated .google.protobuf.Any args = 3;</code>
     * @param value The args to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addArgs")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArgsProxy>.add(value: com.google.protobuf.Any) {
      _builder.addArgs(value)
    }
    /**
     * <code>repeated .google.protobuf.Any args = 3;</code>
     * @param value The args to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignArgs")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArgsProxy>.plusAssign(value: com.google.protobuf.Any) {
      add(value)
    }
    /**
     * <code>repeated .google.protobuf.Any args = 3;</code>
     * @param values The args to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllArgs")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArgsProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.Any>) {
      _builder.addAllArgs(values)
    }
    /**
     * <code>repeated .google.protobuf.Any args = 3;</code>
     * @param values The args to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllArgs")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArgsProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.Any>) {
      addAll(values)
    }
    /**
     * <code>repeated .google.protobuf.Any args = 3;</code>
     * @param index The index to set the value at.
     * @param value The args to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setArgs")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArgsProxy>.set(index: kotlin.Int, value: com.google.protobuf.Any) {
      _builder.setArgs(index, value)
    }
    /**
     * <code>repeated .google.protobuf.Any args = 3;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearArgs")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArgsProxy>.clear() {
      _builder.clearArgs()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun testrunner.expressions.TestExpressions.ConstructorCall.copy(block: testrunner.expressions.ConstructorCallKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.ConstructorCall =
  testrunner.expressions.ConstructorCallKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val testrunner.expressions.TestExpressions.ConstructorCallOrBuilder.methodOrNull: testrunner.expressions.TestExpressions.MethodRepr?
  get() = if (hasMethod()) getMethod() else null

public val testrunner.expressions.TestExpressions.ConstructorCallOrBuilder.returnTypeOrNull: testrunner.expressions.TestExpressions.TypeRepr?
  get() = if (hasReturnType()) getReturnType() else null

