//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: test-expressions.proto

package testrunner.expressions;

@kotlin.jvm.JvmName("-initializefieldRepr")
public inline fun fieldRepr(block: testrunner.expressions.FieldReprKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.FieldRepr =
  testrunner.expressions.FieldReprKt.Dsl._create(testrunner.expressions.TestExpressions.FieldRepr.newBuilder()).apply { block() }._build()
public object FieldReprKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: testrunner.expressions.TestExpressions.FieldRepr.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: testrunner.expressions.TestExpressions.FieldRepr.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): testrunner.expressions.TestExpressions.FieldRepr = _builder.build()

    /**
     * <code>.TypeRepr typeRepr = 1;</code>
     */
    public var typeRepr: testrunner.expressions.TestExpressions.TypeRepr
      @JvmName("getTypeRepr")
      get() = _builder.getTypeRepr()
      @JvmName("setTypeRepr")
      set(value) {
        _builder.setTypeRepr(value)
      }
    /**
     * <code>.TypeRepr typeRepr = 1;</code>
     */
    public fun clearTypeRepr() {
      _builder.clearTypeRepr()
    }
    /**
     * <code>.TypeRepr typeRepr = 1;</code>
     * @return Whether the typeRepr field is set.
     */
    public fun hasTypeRepr(): kotlin.Boolean {
      return _builder.hasTypeRepr()
    }

    /**
     * <code>string name = 2;</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>string name = 2;</code>
     */
    public fun clearName() {
      _builder.clearName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun testrunner.expressions.TestExpressions.FieldRepr.copy(block: testrunner.expressions.FieldReprKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.FieldRepr =
  testrunner.expressions.FieldReprKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val testrunner.expressions.TestExpressions.FieldReprOrBuilder.typeReprOrNull: testrunner.expressions.TestExpressions.TypeRepr?
  get() = if (hasTypeRepr()) getTypeRepr() else null

