//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: test-expressions.proto

package testrunner.expressions;

@kotlin.jvm.JvmName("-initializeilTest")
public inline fun ilTest(block: testrunner.expressions.IlTestKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.IlTest =
  testrunner.expressions.IlTestKt.Dsl._create(testrunner.expressions.TestExpressions.IlTest.newBuilder()).apply { block() }._build()
public object IlTestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: testrunner.expressions.TestExpressions.IlTest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: testrunner.expressions.TestExpressions.IlTest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): testrunner.expressions.TestExpressions.IlTest = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ArrangeStmtsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.Any arrangeStmts = 1;</code>
     */
     public val arrangeStmts: com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArrangeStmtsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getArrangeStmtsList()
      )
    /**
     * <code>repeated .google.protobuf.Any arrangeStmts = 1;</code>
     * @param value The arrangeStmts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addArrangeStmts")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArrangeStmtsProxy>.add(value: com.google.protobuf.Any) {
      _builder.addArrangeStmts(value)
    }
    /**
     * <code>repeated .google.protobuf.Any arrangeStmts = 1;</code>
     * @param value The arrangeStmts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignArrangeStmts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArrangeStmtsProxy>.plusAssign(value: com.google.protobuf.Any) {
      add(value)
    }
    /**
     * <code>repeated .google.protobuf.Any arrangeStmts = 1;</code>
     * @param values The arrangeStmts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllArrangeStmts")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArrangeStmtsProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.Any>) {
      _builder.addAllArrangeStmts(values)
    }
    /**
     * <code>repeated .google.protobuf.Any arrangeStmts = 1;</code>
     * @param values The arrangeStmts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllArrangeStmts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArrangeStmtsProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.Any>) {
      addAll(values)
    }
    /**
     * <code>repeated .google.protobuf.Any arrangeStmts = 1;</code>
     * @param index The index to set the value at.
     * @param value The arrangeStmts to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setArrangeStmts")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArrangeStmtsProxy>.set(index: kotlin.Int, value: com.google.protobuf.Any) {
      _builder.setArrangeStmts(index, value)
    }
    /**
     * <code>repeated .google.protobuf.Any arrangeStmts = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearArrangeStmts")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArrangeStmtsProxy>.clear() {
      _builder.clearArrangeStmts()
    }


    /**
     * <code>.google.protobuf.Any call = 2;</code>
     */
    public var call: com.google.protobuf.Any
      @JvmName("getCall")
      get() = _builder.getCall()
      @JvmName("setCall")
      set(value) {
        _builder.setCall(value)
      }
    /**
     * <code>.google.protobuf.Any call = 2;</code>
     */
    public fun clearCall() {
      _builder.clearCall()
    }
    /**
     * <code>.google.protobuf.Any call = 2;</code>
     * @return Whether the call field is set.
     */
    public fun hasCall(): kotlin.Boolean {
      return _builder.hasCall()
    }

    /**
     * <code>optional .google.protobuf.Any expectedResult = 3;</code>
     */
    public var expectedResult: com.google.protobuf.Any
      @JvmName("getExpectedResult")
      get() = _builder.getExpectedResult()
      @JvmName("setExpectedResult")
      set(value) {
        _builder.setExpectedResult(value)
      }
    /**
     * <code>optional .google.protobuf.Any expectedResult = 3;</code>
     */
    public fun clearExpectedResult() {
      _builder.clearExpectedResult()
    }
    /**
     * <code>optional .google.protobuf.Any expectedResult = 3;</code>
     * @return Whether the expectedResult field is set.
     */
    public fun hasExpectedResult(): kotlin.Boolean {
      return _builder.hasExpectedResult()
    }
    public val IlTestKt.Dsl.expectedResultOrNull: com.google.protobuf.Any?
      get() = _builder.expectedResultOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun testrunner.expressions.TestExpressions.IlTest.copy(block: testrunner.expressions.IlTestKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.IlTest =
  testrunner.expressions.IlTestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val testrunner.expressions.TestExpressions.IlTestOrBuilder.callOrNull: com.google.protobuf.Any?
  get() = if (hasCall()) getCall() else null

public val testrunner.expressions.TestExpressions.IlTestOrBuilder.expectedResultOrNull: com.google.protobuf.Any?
  get() = if (hasExpectedResult()) getExpectedResult() else null

