//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: test-expressions.proto

package testrunner.expressions;

@kotlin.jvm.JvmName("-initializeilTypeInstance")
public inline fun ilTypeInstance(block: testrunner.expressions.IlTypeInstanceKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.IlTypeInstance =
  testrunner.expressions.IlTypeInstanceKt.Dsl._create(testrunner.expressions.TestExpressions.IlTypeInstance.newBuilder()).apply { block() }._build()
public object IlTypeInstanceKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: testrunner.expressions.TestExpressions.IlTypeInstance.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: testrunner.expressions.TestExpressions.IlTypeInstance.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): testrunner.expressions.TestExpressions.IlTypeInstance = _builder.build()

    /**
     * <code>.TypeRepr type = 1;</code>
     */
    public var type: testrunner.expressions.TestExpressions.TypeRepr
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    /**
     * <code>.TypeRepr type = 1;</code>
     */
    public fun clearType() {
      _builder.clearType()
    }
    /**
     * <code>.TypeRepr type = 1;</code>
     * @return Whether the type field is set.
     */
    public fun hasType(): kotlin.Boolean {
      return _builder.hasType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun testrunner.expressions.TestExpressions.IlTypeInstance.copy(block: testrunner.expressions.IlTypeInstanceKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.IlTypeInstance =
  testrunner.expressions.IlTypeInstanceKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val testrunner.expressions.TestExpressions.IlTypeInstanceOrBuilder.typeOrNull: testrunner.expressions.TestExpressions.TypeRepr?
  get() = if (hasType()) getType() else null

