//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: test-expressions.proto

package testrunner.expressions;

@kotlin.jvm.JvmName("-initializeinstanceMethodCall")
public inline fun instanceMethodCall(block: testrunner.expressions.InstanceMethodCallKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.InstanceMethodCall =
  testrunner.expressions.InstanceMethodCallKt.Dsl._create(testrunner.expressions.TestExpressions.InstanceMethodCall.newBuilder()).apply { block() }._build()
public object InstanceMethodCallKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: testrunner.expressions.TestExpressions.InstanceMethodCall.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: testrunner.expressions.TestExpressions.InstanceMethodCall.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): testrunner.expressions.TestExpressions.InstanceMethodCall = _builder.build()

    /**
     * <code>.MethodRepr methodRepr = 1;</code>
     */
    public var methodRepr: testrunner.expressions.TestExpressions.MethodRepr
      @JvmName("getMethodRepr")
      get() = _builder.getMethodRepr()
      @JvmName("setMethodRepr")
      set(value) {
        _builder.setMethodRepr(value)
      }
    /**
     * <code>.MethodRepr methodRepr = 1;</code>
     */
    public fun clearMethodRepr() {
      _builder.clearMethodRepr()
    }
    /**
     * <code>.MethodRepr methodRepr = 1;</code>
     * @return Whether the methodRepr field is set.
     */
    public fun hasMethodRepr(): kotlin.Boolean {
      return _builder.hasMethodRepr()
    }

    /**
     * <code>.TypeRepr returnTypeRepr = 2;</code>
     */
    public var returnTypeRepr: testrunner.expressions.TestExpressions.TypeRepr
      @JvmName("getReturnTypeRepr")
      get() = _builder.getReturnTypeRepr()
      @JvmName("setReturnTypeRepr")
      set(value) {
        _builder.setReturnTypeRepr(value)
      }
    /**
     * <code>.TypeRepr returnTypeRepr = 2;</code>
     */
    public fun clearReturnTypeRepr() {
      _builder.clearReturnTypeRepr()
    }
    /**
     * <code>.TypeRepr returnTypeRepr = 2;</code>
     * @return Whether the returnTypeRepr field is set.
     */
    public fun hasReturnTypeRepr(): kotlin.Boolean {
      return _builder.hasReturnTypeRepr()
    }

    /**
     * <code>.google.protobuf.Any instance = 3;</code>
     */
    public var instance: com.google.protobuf.Any
      @JvmName("getInstance")
      get() = _builder.getInstance()
      @JvmName("setInstance")
      set(value) {
        _builder.setInstance(value)
      }
    /**
     * <code>.google.protobuf.Any instance = 3;</code>
     */
    public fun clearInstance() {
      _builder.clearInstance()
    }
    /**
     * <code>.google.protobuf.Any instance = 3;</code>
     * @return Whether the instance field is set.
     */
    public fun hasInstance(): kotlin.Boolean {
      return _builder.hasInstance()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ArgsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.Any args = 4;</code>
     */
     public val args: com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArgsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getArgsList()
      )
    /**
     * <code>repeated .google.protobuf.Any args = 4;</code>
     * @param value The args to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addArgs")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArgsProxy>.add(value: com.google.protobuf.Any) {
      _builder.addArgs(value)
    }
    /**
     * <code>repeated .google.protobuf.Any args = 4;</code>
     * @param value The args to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignArgs")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArgsProxy>.plusAssign(value: com.google.protobuf.Any) {
      add(value)
    }
    /**
     * <code>repeated .google.protobuf.Any args = 4;</code>
     * @param values The args to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllArgs")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArgsProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.Any>) {
      _builder.addAllArgs(values)
    }
    /**
     * <code>repeated .google.protobuf.Any args = 4;</code>
     * @param values The args to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllArgs")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArgsProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.Any>) {
      addAll(values)
    }
    /**
     * <code>repeated .google.protobuf.Any args = 4;</code>
     * @param index The index to set the value at.
     * @param value The args to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setArgs")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArgsProxy>.set(index: kotlin.Int, value: com.google.protobuf.Any) {
      _builder.setArgs(index, value)
    }
    /**
     * <code>repeated .google.protobuf.Any args = 4;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearArgs")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, ArgsProxy>.clear() {
      _builder.clearArgs()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun testrunner.expressions.TestExpressions.InstanceMethodCall.copy(block: testrunner.expressions.InstanceMethodCallKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.InstanceMethodCall =
  testrunner.expressions.InstanceMethodCallKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val testrunner.expressions.TestExpressions.InstanceMethodCallOrBuilder.methodReprOrNull: testrunner.expressions.TestExpressions.MethodRepr?
  get() = if (hasMethodRepr()) getMethodRepr() else null

public val testrunner.expressions.TestExpressions.InstanceMethodCallOrBuilder.returnTypeReprOrNull: testrunner.expressions.TestExpressions.TypeRepr?
  get() = if (hasReturnTypeRepr()) getReturnTypeRepr() else null

public val testrunner.expressions.TestExpressions.InstanceMethodCallOrBuilder.instanceOrNull: com.google.protobuf.Any?
  get() = if (hasInstance()) getInstance() else null

