//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: test-expressions.proto

package testrunner.expressions;

@kotlin.jvm.JvmName("-initializenullConst")
public inline fun nullConst(block: testrunner.expressions.NullConstKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.NullConst =
  testrunner.expressions.NullConstKt.Dsl._create(testrunner.expressions.TestExpressions.NullConst.newBuilder()).apply { block() }._build()
public object NullConstKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: testrunner.expressions.TestExpressions.NullConst.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: testrunner.expressions.TestExpressions.NullConst.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): testrunner.expressions.TestExpressions.NullConst = _builder.build()

    /**
     * <code>.TypeRepr typeRepr = 1;</code>
     */
    public var typeRepr: testrunner.expressions.TestExpressions.TypeRepr
      @JvmName("getTypeRepr")
      get() = _builder.getTypeRepr()
      @JvmName("setTypeRepr")
      set(value) {
        _builder.setTypeRepr(value)
      }
    /**
     * <code>.TypeRepr typeRepr = 1;</code>
     */
    public fun clearTypeRepr() {
      _builder.clearTypeRepr()
    }
    /**
     * <code>.TypeRepr typeRepr = 1;</code>
     * @return Whether the typeRepr field is set.
     */
    public fun hasTypeRepr(): kotlin.Boolean {
      return _builder.hasTypeRepr()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun testrunner.expressions.TestExpressions.NullConst.copy(block: testrunner.expressions.NullConstKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.NullConst =
  testrunner.expressions.NullConstKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val testrunner.expressions.TestExpressions.NullConstOrBuilder.typeReprOrNull: testrunner.expressions.TestExpressions.TypeRepr?
  get() = if (hasTypeRepr()) getTypeRepr() else null

