//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: test-expressions.proto

package testrunner.expressions;

@kotlin.jvm.JvmName("-initializeobjectInstance")
public inline fun objectInstance(block: testrunner.expressions.ObjectInstanceKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.ObjectInstance =
  testrunner.expressions.ObjectInstanceKt.Dsl._create(testrunner.expressions.TestExpressions.ObjectInstance.newBuilder()).apply { block() }._build()
public object ObjectInstanceKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: testrunner.expressions.TestExpressions.ObjectInstance.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: testrunner.expressions.TestExpressions.ObjectInstance.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): testrunner.expressions.TestExpressions.ObjectInstance = _builder.build()

    /**
     * <code>.TypeRepr typeRepr = 1;</code>
     */
    public var typeRepr: testrunner.expressions.TestExpressions.TypeRepr
      @JvmName("getTypeRepr")
      get() = _builder.getTypeRepr()
      @JvmName("setTypeRepr")
      set(value) {
        _builder.setTypeRepr(value)
      }
    /**
     * <code>.TypeRepr typeRepr = 1;</code>
     */
    public fun clearTypeRepr() {
      _builder.clearTypeRepr()
    }
    /**
     * <code>.TypeRepr typeRepr = 1;</code>
     * @return Whether the typeRepr field is set.
     */
    public fun hasTypeRepr(): kotlin.Boolean {
      return _builder.hasTypeRepr()
    }

    /**
     * <code>int32 address = 2;</code>
     */
    public var address: kotlin.Int
      @JvmName("getAddress")
      get() = _builder.getAddress()
      @JvmName("setAddress")
      set(value) {
        _builder.setAddress(value)
      }
    /**
     * <code>int32 address = 2;</code>
     */
    public fun clearAddress() {
      _builder.clearAddress()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun testrunner.expressions.TestExpressions.ObjectInstance.copy(block: testrunner.expressions.ObjectInstanceKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.ObjectInstance =
  testrunner.expressions.ObjectInstanceKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val testrunner.expressions.TestExpressions.ObjectInstanceOrBuilder.typeReprOrNull: testrunner.expressions.TestExpressions.TypeRepr?
  get() = if (hasTypeRepr()) getTypeRepr() else null

