//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: test-expressions.proto

package testrunner.expressions;

@kotlin.jvm.JvmName("-initializesetArrayIndex")
public inline fun setArrayIndex(block: testrunner.expressions.SetArrayIndexKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.SetArrayIndex =
  testrunner.expressions.SetArrayIndexKt.Dsl._create(testrunner.expressions.TestExpressions.SetArrayIndex.newBuilder()).apply { block() }._build()
public object SetArrayIndexKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: testrunner.expressions.TestExpressions.SetArrayIndex.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: testrunner.expressions.TestExpressions.SetArrayIndex.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): testrunner.expressions.TestExpressions.SetArrayIndex = _builder.build()

    /**
     * <code>.ArrayInstance instance = 1;</code>
     */
    public var instance: testrunner.expressions.TestExpressions.ArrayInstance
      @JvmName("getInstance")
      get() = _builder.getInstance()
      @JvmName("setInstance")
      set(value) {
        _builder.setInstance(value)
      }
    /**
     * <code>.ArrayInstance instance = 1;</code>
     */
    public fun clearInstance() {
      _builder.clearInstance()
    }
    /**
     * <code>.ArrayInstance instance = 1;</code>
     * @return Whether the instance field is set.
     */
    public fun hasInstance(): kotlin.Boolean {
      return _builder.hasInstance()
    }

    /**
     * <code>int32 index = 2;</code>
     */
    public var index: kotlin.Int
      @JvmName("getIndex")
      get() = _builder.getIndex()
      @JvmName("setIndex")
      set(value) {
        _builder.setIndex(value)
      }
    /**
     * <code>int32 index = 2;</code>
     */
    public fun clearIndex() {
      _builder.clearIndex()
    }

    /**
     * <code>.google.protobuf.Any value = 3;</code>
     */
    public var value: com.google.protobuf.Any
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * <code>.google.protobuf.Any value = 3;</code>
     */
    public fun clearValue() {
      _builder.clearValue()
    }
    /**
     * <code>.google.protobuf.Any value = 3;</code>
     * @return Whether the value field is set.
     */
    public fun hasValue(): kotlin.Boolean {
      return _builder.hasValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun testrunner.expressions.TestExpressions.SetArrayIndex.copy(block: testrunner.expressions.SetArrayIndexKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.SetArrayIndex =
  testrunner.expressions.SetArrayIndexKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val testrunner.expressions.TestExpressions.SetArrayIndexOrBuilder.instanceOrNull: testrunner.expressions.TestExpressions.ArrayInstance?
  get() = if (hasInstance()) getInstance() else null

public val testrunner.expressions.TestExpressions.SetArrayIndexOrBuilder.valueOrNull: com.google.protobuf.Any?
  get() = if (hasValue()) getValue() else null

