//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: test-expressions.proto

package testrunner.expressions;

@kotlin.jvm.JvmName("-initializesetObjectField")
public inline fun setObjectField(block: testrunner.expressions.SetObjectFieldKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.SetObjectField =
  testrunner.expressions.SetObjectFieldKt.Dsl._create(testrunner.expressions.TestExpressions.SetObjectField.newBuilder()).apply { block() }._build()
public object SetObjectFieldKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: testrunner.expressions.TestExpressions.SetObjectField.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: testrunner.expressions.TestExpressions.SetObjectField.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): testrunner.expressions.TestExpressions.SetObjectField = _builder.build()

    /**
     * <code>.ObjectInstance instance = 1;</code>
     */
    public var instance: testrunner.expressions.TestExpressions.ObjectInstance
      @JvmName("getInstance")
      get() = _builder.getInstance()
      @JvmName("setInstance")
      set(value) {
        _builder.setInstance(value)
      }
    /**
     * <code>.ObjectInstance instance = 1;</code>
     */
    public fun clearInstance() {
      _builder.clearInstance()
    }
    /**
     * <code>.ObjectInstance instance = 1;</code>
     * @return Whether the instance field is set.
     */
    public fun hasInstance(): kotlin.Boolean {
      return _builder.hasInstance()
    }

    /**
     * <code>.FieldRepr fieldRepr = 2;</code>
     */
    public var fieldRepr: testrunner.expressions.TestExpressions.FieldRepr
      @JvmName("getFieldRepr")
      get() = _builder.getFieldRepr()
      @JvmName("setFieldRepr")
      set(value) {
        _builder.setFieldRepr(value)
      }
    /**
     * <code>.FieldRepr fieldRepr = 2;</code>
     */
    public fun clearFieldRepr() {
      _builder.clearFieldRepr()
    }
    /**
     * <code>.FieldRepr fieldRepr = 2;</code>
     * @return Whether the fieldRepr field is set.
     */
    public fun hasFieldRepr(): kotlin.Boolean {
      return _builder.hasFieldRepr()
    }

    /**
     * <code>.google.protobuf.Any value = 3;</code>
     */
    public var value: com.google.protobuf.Any
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * <code>.google.protobuf.Any value = 3;</code>
     */
    public fun clearValue() {
      _builder.clearValue()
    }
    /**
     * <code>.google.protobuf.Any value = 3;</code>
     * @return Whether the value field is set.
     */
    public fun hasValue(): kotlin.Boolean {
      return _builder.hasValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun testrunner.expressions.TestExpressions.SetObjectField.copy(block: testrunner.expressions.SetObjectFieldKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.SetObjectField =
  testrunner.expressions.SetObjectFieldKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val testrunner.expressions.TestExpressions.SetObjectFieldOrBuilder.instanceOrNull: testrunner.expressions.TestExpressions.ObjectInstance?
  get() = if (hasInstance()) getInstance() else null

public val testrunner.expressions.TestExpressions.SetObjectFieldOrBuilder.fieldReprOrNull: testrunner.expressions.TestExpressions.FieldRepr?
  get() = if (hasFieldRepr()) getFieldRepr() else null

public val testrunner.expressions.TestExpressions.SetObjectFieldOrBuilder.valueOrNull: com.google.protobuf.Any?
  get() = if (hasValue()) getValue() else null

