//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: test-expressions.proto

package testrunner.expressions;

@kotlin.jvm.JvmName("-initializetypeRepr")
public inline fun typeRepr(block: testrunner.expressions.TypeReprKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.TypeRepr =
  testrunner.expressions.TypeReprKt.Dsl._create(testrunner.expressions.TestExpressions.TypeRepr.newBuilder()).apply { block() }._build()
public object TypeReprKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: testrunner.expressions.TestExpressions.TypeRepr.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: testrunner.expressions.TestExpressions.TypeRepr.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): testrunner.expressions.TestExpressions.TypeRepr = _builder.build()

    /**
     * <code>string asm = 1;</code>
     */
    public var asm: kotlin.String
      @JvmName("getAsm")
      get() = _builder.getAsm()
      @JvmName("setAsm")
      set(value) {
        _builder.setAsm(value)
      }
    /**
     * <code>string asm = 1;</code>
     */
    public fun clearAsm() {
      _builder.clearAsm()
    }

    /**
     * <code>int32 moduleToken = 2;</code>
     */
    public var moduleToken: kotlin.Int
      @JvmName("getModuleToken")
      get() = _builder.getModuleToken()
      @JvmName("setModuleToken")
      set(value) {
        _builder.setModuleToken(value)
      }
    /**
     * <code>int32 moduleToken = 2;</code>
     */
    public fun clearModuleToken() {
      _builder.clearModuleToken()
    }

    /**
     * <code>int32 typeToken = 3;</code>
     */
    public var typeToken: kotlin.Int
      @JvmName("getTypeToken")
      get() = _builder.getTypeToken()
      @JvmName("setTypeToken")
      set(value) {
        _builder.setTypeToken(value)
      }
    /**
     * <code>int32 typeToken = 3;</code>
     */
    public fun clearTypeToken() {
      _builder.clearTypeToken()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class GenericArgsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .TypeRepr genericArgs = 4;</code>
     */
     public val genericArgs: com.google.protobuf.kotlin.DslList<testrunner.expressions.TestExpressions.TypeRepr, GenericArgsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getGenericArgsList()
      )
    /**
     * <code>repeated .TypeRepr genericArgs = 4;</code>
     * @param value The genericArgs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addGenericArgs")
    public fun com.google.protobuf.kotlin.DslList<testrunner.expressions.TestExpressions.TypeRepr, GenericArgsProxy>.add(value: testrunner.expressions.TestExpressions.TypeRepr) {
      _builder.addGenericArgs(value)
    }
    /**
     * <code>repeated .TypeRepr genericArgs = 4;</code>
     * @param value The genericArgs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignGenericArgs")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<testrunner.expressions.TestExpressions.TypeRepr, GenericArgsProxy>.plusAssign(value: testrunner.expressions.TestExpressions.TypeRepr) {
      add(value)
    }
    /**
     * <code>repeated .TypeRepr genericArgs = 4;</code>
     * @param values The genericArgs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllGenericArgs")
    public fun com.google.protobuf.kotlin.DslList<testrunner.expressions.TestExpressions.TypeRepr, GenericArgsProxy>.addAll(values: kotlin.collections.Iterable<testrunner.expressions.TestExpressions.TypeRepr>) {
      _builder.addAllGenericArgs(values)
    }
    /**
     * <code>repeated .TypeRepr genericArgs = 4;</code>
     * @param values The genericArgs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllGenericArgs")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<testrunner.expressions.TestExpressions.TypeRepr, GenericArgsProxy>.plusAssign(values: kotlin.collections.Iterable<testrunner.expressions.TestExpressions.TypeRepr>) {
      addAll(values)
    }
    /**
     * <code>repeated .TypeRepr genericArgs = 4;</code>
     * @param index The index to set the value at.
     * @param value The genericArgs to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setGenericArgs")
    public operator fun com.google.protobuf.kotlin.DslList<testrunner.expressions.TestExpressions.TypeRepr, GenericArgsProxy>.set(index: kotlin.Int, value: testrunner.expressions.TestExpressions.TypeRepr) {
      _builder.setGenericArgs(index, value)
    }
    /**
     * <code>repeated .TypeRepr genericArgs = 4;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearGenericArgs")
    public fun com.google.protobuf.kotlin.DslList<testrunner.expressions.TestExpressions.TypeRepr, GenericArgsProxy>.clear() {
      _builder.clearGenericArgs()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun testrunner.expressions.TestExpressions.TypeRepr.copy(block: testrunner.expressions.TypeReprKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.TypeRepr =
  testrunner.expressions.TypeReprKt.Dsl._create(this.toBuilder()).apply { block() }._build()

