//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: test-expressions.proto

package testrunner.expressions;

@kotlin.jvm.JvmName("-initializeuInt32Const")
public inline fun uInt32Const(block: testrunner.expressions.UInt32ConstKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.UInt32Const =
  testrunner.expressions.UInt32ConstKt.Dsl._create(testrunner.expressions.TestExpressions.UInt32Const.newBuilder()).apply { block() }._build()
public object UInt32ConstKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: testrunner.expressions.TestExpressions.UInt32Const.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: testrunner.expressions.TestExpressions.UInt32Const.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): testrunner.expressions.TestExpressions.UInt32Const = _builder.build()

    /**
     * <code>sint32 value = 1;</code>
     */
    public var value: kotlin.Int
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * <code>sint32 value = 1;</code>
     */
    public fun clearValue() {
      _builder.clearValue()
    }

    /**
     * <code>.TypeRepr typeRepr = 2;</code>
     */
    public var typeRepr: testrunner.expressions.TestExpressions.TypeRepr
      @JvmName("getTypeRepr")
      get() = _builder.getTypeRepr()
      @JvmName("setTypeRepr")
      set(value) {
        _builder.setTypeRepr(value)
      }
    /**
     * <code>.TypeRepr typeRepr = 2;</code>
     */
    public fun clearTypeRepr() {
      _builder.clearTypeRepr()
    }
    /**
     * <code>.TypeRepr typeRepr = 2;</code>
     * @return Whether the typeRepr field is set.
     */
    public fun hasTypeRepr(): kotlin.Boolean {
      return _builder.hasTypeRepr()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun testrunner.expressions.TestExpressions.UInt32Const.copy(block: testrunner.expressions.UInt32ConstKt.Dsl.() -> kotlin.Unit): testrunner.expressions.TestExpressions.UInt32Const =
  testrunner.expressions.UInt32ConstKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val testrunner.expressions.TestExpressions.UInt32ConstOrBuilder.typeReprOrNull: testrunner.expressions.TestExpressions.TypeRepr?
  get() = if (hasTypeRepr()) getTypeRepr() else null

